services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "5239:8080"

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    depends_on:
      - api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      AlertsApi__BaseUrl: http://api:8080
    ports:
      - "5111:8080"